pub(crate) mod diagnostics;

use std::collections::HashMap;
use std::sync::Arc;

use tower_lsp_server::lsp_types::{Diagnostic, Uri};

use self::diagnostics::DiagnosticBundle;
use crate::analysis::AnalysisSnapshot;
use crate::navigation::FunctionIdentity;

#[derive(Debug)]
struct RootAnalysis {
    snapshot: AnalysisSnapshot,
    diagnostics: DiagnosticBundle,
}

#[derive(Clone, Debug, Default)]
struct DocumentState {
    generation: u64,
    open: bool,
    text: Option<Arc<str>>,
    version: Option<i32>,
}

pub(crate) type AnalysisGeneration = u64;

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct AnalysisInput {
    pub uri: Uri,
    pub text: Arc<str>,
    pub version: Option<i32>,
    pub generation: AnalysisGeneration,
}

/// One atomic diagnostic publication generated by replacing or removing a root analysis.
#[derive(Debug)]
pub struct DiagnosticUpdate {
    pub uri: Uri,
    pub diagnostics: Vec<Diagnostic>,
    pub version: Option<i32>,
}

/// Owns open-root analyses and all policy for cross-root diagnostic aggregation.
#[derive(Debug, Default)]
pub struct WorkspaceState {
    roots: HashMap<Uri, RootAnalysis>,
    documents: HashMap<Uri, DocumentState>,
}

impl WorkspaceState {
    pub fn get(&self, uri: &Uri) -> Option<&AnalysisSnapshot> {
        self.roots.get(uri).map(|root| &root.snapshot)
    }

    pub fn values(&self) -> impl Iterator<Item = &AnalysisSnapshot> {
        self.roots.values().map(|root| &root.snapshot)
    }

    pub(crate) fn begin_open(
        &mut self,
        uri: &Uri,
        text: &str,
        version: Option<i32>,
    ) -> AnalysisInput {
        let text = Arc::<str>::from(text);
        let state = self.documents.entry(uri.clone()).or_default();
        state.generation = state.generation.wrapping_add(1);
        state.open = true;
        state.text = Some(Arc::clone(&text));
        state.version = version;
        AnalysisInput {
            uri: uri.clone(),
            text,
            version,
            generation: state.generation,
        }
    }

    pub(crate) fn begin_change(
        &mut self,
        uri: &Uri,
        text: &str,
        version: Option<i32>,
    ) -> Option<AnalysisInput> {
        let state = self.documents.get_mut(uri)?;
        if !state.open {
            return None;
        }
        if matches!(
            (version, state.version),
            (Some(incoming), Some(current)) if incoming < current
        ) {
            return None;
        }
        let text = Arc::<str>::from(text);
        state.generation = state.generation.wrapping_add(1);
        state.text = Some(Arc::clone(&text));
        if version.is_some() {
            state.version = version;
        }
        Some(AnalysisInput {
            uri: uri.clone(),
            text,
            version: state.version,
            generation: state.generation,
        })
    }

    /// Snapshot all open buffers and reserve their analysis generations atomically.
    pub(crate) fn begin_reanalysis(&mut self) -> Vec<AnalysisInput> {
        self.documents
            .iter_mut()
            .filter_map(|(uri, state)| {
                if !state.open {
                    return None;
                }
                let text = Arc::clone(
                    state
                        .text
                        .as_ref()
                        .expect("open documents retain their source text"),
                );
                state.generation = state.generation.wrapping_add(1);
                Some(AnalysisInput {
                    uri: uri.clone(),
                    text,
                    version: state.version,
                    generation: state.generation,
                })
            })
            .collect()
    }

    pub(crate) fn begin_close(&mut self, uri: &Uri) -> Option<AnalysisGeneration> {
        let state = self.documents.get_mut(uri)?;
        if !state.open {
            return None;
        }
        state.generation = state.generation.wrapping_add(1);
        state.open = false;
        state.text = None;
        state.version = None;
        Some(state.generation)
    }

    fn is_current(&self, uri: &Uri, generation: AnalysisGeneration, open: bool) -> bool {
        self.documents
            .get(uri)
            .is_some_and(|state| state.generation == generation && state.open == open)
    }

    pub(crate) fn replace_if_current(
        &mut self,
        origin: &Uri,
        snapshot: AnalysisSnapshot,
        incoming_version: Option<i32>,
        generation: AnalysisGeneration,
    ) -> Option<Vec<DiagnosticUpdate>> {
        self.is_current(origin, generation, true)
            .then(|| self.replace_inner(origin, snapshot, incoming_version))
    }

    pub(crate) fn remove_if_current(
        &mut self,
        origin: &Uri,
        generation: AnalysisGeneration,
    ) -> Option<Vec<DiagnosticUpdate>> {
        self.is_current(origin, generation, false)
            .then(|| self.remove(origin))
    }

    pub(crate) fn diagnostics_if_current(
        &self,
        uri: Uri,
        diagnostics: Vec<Diagnostic>,
        version: Option<i32>,
        generation: AnalysisGeneration,
    ) -> Option<Vec<DiagnosticUpdate>> {
        self.is_current(&uri, generation, true).then(|| {
            vec![DiagnosticUpdate {
                uri,
                diagnostics,
                version,
            }]
        })
    }

    pub(crate) fn find_references_to(
        &self,
        target: &FunctionIdentity,
    ) -> Vec<tower_lsp_server::lsp_types::Location> {
        let mut locations = self
            .values()
            .filter_map(|snapshot| snapshot.find_references_to(target).ok())
            .flatten()
            .collect::<Vec<_>>();
        locations.sort_unstable_by(|left, right| {
            left.uri
                .as_str()
                .cmp(right.uri.as_str())
                .then(left.range.start.line.cmp(&right.range.start.line))
                .then(left.range.start.character.cmp(&right.range.start.character))
                .then(left.range.end.line.cmp(&right.range.end.line))
                .then(left.range.end.character.cmp(&right.range.end.character))
        });
        locations.dedup();
        locations
    }

    fn replace_inner(
        &mut self,
        origin: &Uri,
        mut snapshot: AnalysisSnapshot,
        version: Option<i32>,
    ) -> Vec<DiagnosticUpdate> {
        snapshot.version = version;
        let diagnostics = DiagnosticBundle::from_snapshot(&snapshot);
        let mut affected = self
            .roots
            .get(origin)
            .into_iter()
            .flat_map(|root| root.diagnostics.uris().cloned())
            .chain(diagnostics.uris().cloned())
            .collect::<Vec<_>>();
        affected.push(origin.clone());

        self.roots.insert(
            origin.clone(),
            RootAnalysis {
                snapshot,
                diagnostics,
            },
        );
        self.updates(affected, Some((origin, version)))
    }

    pub fn remove(&mut self, origin: &Uri) -> Vec<DiagnosticUpdate> {
        let mut affected = self
            .roots
            .remove(origin)
            .map(|root| root.diagnostics.uris().cloned().collect::<Vec<_>>())
            .unwrap_or_default();
        affected.push(origin.clone());
        self.updates(affected, None)
    }

    fn updates(
        &self,
        mut affected: Vec<Uri>,
        direct: Option<(&Uri, Option<i32>)>,
    ) -> Vec<DiagnosticUpdate> {
        affected.sort_unstable_by(|left, right| left.as_str().cmp(right.as_str()));
        affected.dedup();
        affected
            .into_iter()
            .map(|uri| DiagnosticUpdate {
                diagnostics: self.diagnostics_for(&uri),
                version: direct
                    .filter(|(direct_uri, _)| *direct_uri == &uri)
                    .and_then(|(_, version)| version),
                uri,
            })
            .collect()
    }

    fn diagnostics_for(&self, target: &Uri) -> Vec<Diagnostic> {
        // An open file's unsaved analysis is authoritative over saved dependency copies.
        if let Some(root) = self.roots.get(target) {
            return root
                .diagnostics
                .get(target)
                .map(<[Diagnostic]>::to_vec)
                .unwrap_or_default();
        }

        let mut origins = self.roots.iter().collect::<Vec<_>>();
        origins.sort_unstable_by(|(left, _), (right, _)| left.as_str().cmp(right.as_str()));
        let mut diagnostics = Vec::new();
        for (_, root) in origins {
            let Some(contributed) = root.diagnostics.get(target) else {
                continue;
            };
            for diagnostic in contributed {
                if !diagnostics.contains(diagnostic) {
                    diagnostics.push(diagnostic.clone());
                }
            }
        }
        diagnostics
    }
}

#[cfg(test)]
mod tests;
