name: Setup RBMT
description: Install cargo-rbmt and pinned Rust toolchains.

runs:
  using: "composite"
  steps:
    - name: Install cargo-rbmt
      shell: bash
      run: |
        cargo install \
          --git https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools \
          --rev "$(cat "${GITHUB_WORKSPACE}/rbmt-version")" \
          cargo-rbmt \
          --locked

    - name: Install Rust toolchains
      shell: bash
      run: cargo rbmt toolchains
